# Example with new configmaps and secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  argocd.argoproj.io/sync-options: Prune=false
  labels:
    run-type: stable
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run-type: stable
      app: nginx
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        run-type: stable
        app: nginx
    spec:
      containers:
      - image: nginx:1.26-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: nginx-env
        - secretRef:
            name: nginx-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx
spec:
  host: nginx
  subsets:
  - name: stable
    labels:
      run-type: stable
  - name: canary
    labels:
      run-type: canary
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  argocd.argoproj.io/sync-options: Prune=false
  name: nginx-vs
spec:
  hosts:
  - nginx
  http:
  - route:
    - destination:
        host: nginx
        subset: stable
      weight: 100
    - destination:
        host: nginx
        subset: canary
      weight: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env
data:
  APP_NAME: "nginx"
  LEVEL: "debug"
---
# New for canary
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-new
type: Opaque
data:
  PASS: MTIzNA==
---
# New for canary
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-new1-env
data:
  APP_NAME: "nginx-canary"
  LEVEL: "debug"
---
# New for canary
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-new2-env
data:
  APP_NAME: "nginx-canary"
  LEVEL: "debug"


